export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const SELECT_ITEM = "SELECT_ITEM";
export const UNSELECT_ITEM = "UNSELECT_ITEM";

export const SELECT_MULTI_ITEMS = "SELECT_MULTI_ITEMS";
export const UNSELECT_MULTI_ITEMS = "UNSELECT_MULTI_ITEMS";

export const SELECT_DRAWER_ITEM = "SELECT_DRAWER_ITEM";

export const SELECT_SHARE_ITEM = "SELECT_SHARE_ITEM";

export const GET_ALL_ITEMS = "GET_ALL_ITEMS";