# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Boxroom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Boxroom





  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-video', :path => '../node_modules/react-native-video'


  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'ReactNativePayments', :path => '../node_modules/react-native-payments'

end
